engineering: the fundamental of web performance
dwarvesf/brain pull request #108
Opened 2022-10-02 12:26 UTC by zlatanpham

2022-10-03 02:39 UTC, monotykamary approved these changes
LGTM, although maybe tags are a bit too general.

2022-10-03 14:12 UTC, trankhacvy commented
Agree, the tags and the content are a bit general. Could we consider having serial notes for the specific factor of web performance instead of a general one?
Some examples: 
- https://web.dev/learn-core-web-vitals/
- https://web.dev/fast/

2022-10-04 03:22 UTC, janrvu requested changes
Please change the date format to YYYY-MM-DD

2022-10-04 03:22 UTC, janrvu commented on Engineering/Frontend/The fundamental of web performance.md
> +date: 2022-02-10
Should be formatted to YYYY-MM-DD => 2022-10-02

2022-10-04 04:54 UTC, tienan92it commented
LGTM

2022-10-04 04:54 UTC, tienan92it approved these changes

2022-10-04 05:13 UTC, zlatanpham commented
> Agree, the tags and the content are a bit general. Could we consider having serial notes for the specific factor of web performance instead of a general one?

Yes, we will have other linked notes for those specific topics. For example, I'm currently writing a note on resource hint.

2022-10-04 05:21 UTC, zlatanpham commented
And about the general content, this is on purpose. I wanted to have our engineers think about web performance at a high level so they can have a broader idea about which path they would go for when trying to optimize for speed.

2022-10-04 05:50 UTC, zlatanpham commented
@monotykamary I think it's good to merge

2022-10-04 09:54 UTC, merged