engineering: singleton design pattern in JS
dwarvesf/brain pull request #110
Opened 2022-10-06 08:58 UTC by chinhld12

#### What's this PR do?

- [x] Singleton design pattern for using in global context

2022-10-11 08:28 UTC, janrvu requested changes
Please update the date (YYYY - MM - DD)

2022-10-20 10:02 UTC, tienan92it commented on Engineering/Frontend/Singleton Design Pattern in Javascript.md
> +- The Singleton is violate to the Single Responsibility Principle, via the SRP definition that a class only should only have one responsibility. But with the singleton pattern, it can carry too many
Another cons of singleton design pattern is difficult to write unit test cases.

2022-10-23 08:41 UTC, tienan92it approved these changes
LGTM

2022-10-26 07:59 UTC, monotykamary approved these changes
LGTM

2022-10-26 07:59 UTC, merged