engineering: Blue-green Deployment
dwarvesf/brain pull request #167
Opened 2023-02-15 22:19 UTC by nguyennh4522

#### What's this PR do?

- [x] Explain what is Blue-green Deployment
- [x] Explain how to implement blue-green deployment
- [x] Compare with other strategies

2023-02-16 03:37 UTC, lmquang approved these changes

2023-02-16 03:37 UTC, lmquang commented
@monotykamary  xem qua r merge giup a nha e

2023-02-28 02:47 UTC, toanbku requested changes

2023-02-28 02:47 UTC, toanbku commented on Engineering/DevOps/Blue-green Deployment.md
> +![[blue-green-deployment-model.gif]]
should be `![alt of image](../../_assets/blue-green-deployment-model.gif)`

2023-02-28 02:47 UTC, toanbku commented on Engineering/DevOps/Blue-green Deployment.md
> +![[bluegreen-compare.png]]
same here

2023-02-28 02:47 UTC, toanbku commented on Engineering/DevOps/Blue-green Deployment.md
> +![[bluegreen-blue-application.png]]
same here

2023-02-28 02:47 UTC, toanbku commented on Engineering/DevOps/Blue-green Deployment.md
> +![[bluegreen-green-application.png]]
same here

2023-02-28 02:55 UTC, zlatanpham approved these changes

2023-02-28 03:02 UTC, merged