communication: the art of body language
dwarvesf/brain pull request #36
Opened 2022-06-23 07:27 UTC by jessyphung

2022-06-26 13:47 UTC, monotykamary commented
https://www.ted.com/talks/amy_cuddy_your_body_language_may_shape_who_you_are/transcript
http://www.permondo.eu/your-body-language-shapes-who-you-are/

There are quite a handful of phrases that are not unique in this note. Please see our contributing document on plagiarism: https://github.com/dwarvesf/brain/blob/master/CONTRIBUTING.md

This is probably just an honest mistake, but please keep in mind that we want the articles to be unique to the world view of the author. Please revise the note to paraphrase and recompose the idea as to how you might say or word it.

2022-06-26 13:53 UTC, monotykamary requested changes

2022-06-26 13:53 UTC, monotykamary commented on Communication/the art of body language.md
> +--
The metadata table should be wrapped with 3 hypens instead of 2.

2022-06-27 08:45 UTC, zlatanpham reviewed
Some nits

2022-06-27 08:45 UTC, zlatanpham commented on Communication/the art of body language.md
> +# What is body language?
```suggestion
## What is body language?

```

2022-06-27 08:45 UTC, zlatanpham commented on Communication/the art of body language.md
> +# The impact of it
```suggestion
## The impact of it

```

2022-06-27 08:45 UTC, zlatanpham commented on Communication/the art of body language.md
> +# How it works?
```suggestion
## How does it work?

```

2022-06-27 08:45 UTC, zlatanpham commented on Communication/the art of body language.md
> +# Advices
```suggestion
## Advice 

```

2022-09-06 08:46 UTC, merged