design: what screens want
dwarvesf/brain pull request #39
Opened 2022-06-24 05:04 UTC by cnhhoang850

#### What's this PR do?

Publishing "What Screens Want" notes

2022-06-24 06:19 UTC, zlatanpham commented
Hey @cnhhoang850, thanks for your contribution. We will have a look soon.

2022-06-26 14:09 UTC, monotykamary requested changes
This was a very inspiring read.

The only thing that needs to be changed is the file extension (`.md` instead of `.d`) with the only minor change is to add some quotations to indicate Frank's famous quote.

2022-06-27 08:32 UTC, cnhhoang850 commented on Design/What Screens Want.d
> +- If something can be anything, it usually becomes everything.
Thanks! Added quotations.

2022-06-27 23:32 UTC, zlatanpham approved these changes

2022-06-27 23:32 UTC, merged

2022-06-27 23:45 UTC, zlatanpham commented
Hi @cnhhoang850, we've published your note at https://brain.d.foundation/Design/What+Screens+Want. Thank you again for your contribution. Did you join our [Discord server](https://discord.com/invite/Y2vvH9rQE4)? We want to reach out and send a small gift to you :)