engineering: domain model in DDD
dwarvesf/brain pull request #42
Opened 2022-06-28 14:58 UTC by R-Jim

#### What's this PR do?

- [x] Domain model in DDD

2022-06-28 15:14 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +[Here is the full overview](obsidian://open?vault=brain&file=Engineering%2FOverview%20of%20Domain%20Driven%20Design)
I think including the recap is kind of unnecessary. Maybe just mention the DDD article from the introduction of Domain model. e.g:

```
In [Domain Driven Design](link), Domain Model is ....
```

2022-06-28 23:37 UTC, monotykamary requested changes

2022-06-28 23:37 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +It is represented by a cluster of events with corresponding commands and the responsible actor.
This statement is not unique and is taken directly from the reference source:
- https://creately.com/blog/diagrams/event-storming/

Please paraphrase this statement.

2022-07-01 05:38 UTC, monotykamary requested changes
Just needs some work on header styling,

otherwise LGTM.

2022-07-01 05:38 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +### Domain model is
https://github.com/dwarvesf/brain/blob/master/CONTRIBUTING.md
Last nit picks; use ## H2 headers as your top level header.

2022-07-01 05:38 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +### Domain model consists of
Likewise, use ## H2 headers to mirror your top level header.

2022-07-01 05:38 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +### Domain events
Likewise, use ## H2 headers to mirror your top level header.

2022-07-01 05:38 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +### Commands
Likewise, use ## H2 headers to mirror your top level header.

2022-07-01 05:38 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +### Aggregrates
Likewise, use ## H2 headers to mirror your top level header.

2022-07-01 05:38 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +### Bounded context
Likewise, use ## H2 headers to mirror your top level header.

2022-07-01 05:38 UTC, monotykamary commented on Engineering/Domain model in Domain Driven Design.md
> +### References
Likewise, use ## H2 headers to mirror your top level header.

2022-07-02 04:38 UTC, zlatanpham requested changes
I've left some suggestions to make the note better formatted.

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +## Domain model is
```suggestion
## What is Domain Model
```

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +Your organized and structured **knowledge of the business problem**. Represents as a diagram, code examples, or written documentation, and **must** be accessible and understandable by **everyone** in
```suggestion
In [Overview of Domain Driven Design | Domain Driven Design], Domain Model is the organized and structured **knowledge of the business problem**. Represents as a diagram, code examples, or written documentation, and **must** be accessible and understandable by **everyone** involved with the project.
```

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +[Overview of Domain Driven Design](https://github.com/dwarvesf/brain/blob/master/Engineering/Overview%20of%20Domain%20Driven%20Design.md)
Remove this

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +## Domain model consists of
```suggestion
## Components of Domain Model
```

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +These are mainly divided into: **Domain events**, **Commands**, **Aggregates**, and **Bounded context**.
```suggestion
The vocabulary and key concepts of the domain, and the relationships among all of the entities. These are mainly divided into: **Domain events**, **Commands**, **Aggregates**, and **Bounded context**.
```

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +## Domain events
```suggestion
### Domain events
```

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +## Commands
```suggestion
### Commands
```

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +## Aggregrates
```suggestion
### Aggregrates
```

2022-07-02 04:38 UTC, zlatanpham commented on Engineering/Domain model in Domain Driven Design.md
> +## Bounded context
```suggestion
### Bounded context
```

2022-07-02 06:18 UTC, zlatanpham approved these changes

2022-07-02 06:18 UTC, merged