engineering: Wrap UIKit using Swift 5.4 @resultBuilder
dwarvesf/brain pull request #59
Opened 2022-08-08 04:56 UTC by viettrungphan

The second part of Building UI with UIKit using Builder pattern (DSL style)

2022-08-09 03:47 UTC, monotykamary requested changes
Format seems OK, but please do avoid pleasantries and advertisements in these notes. Fleeting notes do not target an audience *outside of its context.

There is also a non-trivial amount of spelling errors, which we can help fix up a bit.

2022-08-09 03:47 UTC, monotykamary commented on Engineering/Mobile/Swift 5.4 @resultBuilder.md
> +Happy coding 🧑‍💻!
Please avoid pleasantries in your notes. Brainery notes are close to fleeting notes, which are often semantically not aware of any subject or audience outside its context.

2022-08-26 04:33 UTC, viettrungphan commented on Engineering/Mobile/Swift 5.4 @resultBuilder.md
> +
It's normal in Swift for readability.

2022-08-30 04:34 UTC, zlatanpham approved these changes
Note that I will do a light edit before we publish it.

2022-08-30 04:34 UTC, merged