mobile: iOS bluetooth low energy
dwarvesf/brain pull request #74
Opened 2022-09-05 03:20 UTC by knguyenuit

#### What's this PR do?

- [x] Basic knowledge about the bluetooth low energy in iOS
- [x] Demo connect the iOS device with the Bluetooth device and transfer data

2022-09-05 10:09 UTC, monotykamary requested changes
A great entry, with some small nits such as the duplicate markdown entry, lack of frontmatter, and lack of code highlights. Not too sure how to handle the demo zip, but I think we can organize it on our side.

2022-09-05 10:09 UTC, monotykamary commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +```
Small nit here for code visibility:
\```swift

2022-09-06 03:57 UTC, monotykamary requested changes

2022-09-06 03:57 UTC, monotykamary commented on .gitignore
> +knguyenuit_rsa.pub
Why is this included in the gitignore?

2022-09-06 04:07 UTC, zlatanpham reviewed
Left some comments about the formatting.

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +```
Is this swift language? If so, can you specify `lang` of the block for the sake of sytax highlight?

```suggestion
```swift
```

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    }
I think we can remove the leading space of the whole block
```suggestion
private func handleDataNotify(_ data: Data) {
    var textJson = String(data: data, encoding: .utf8) ?? ""
    if let indexRemove = textJson.firstIndex(where: { $0 == "<" }) {
        textJson.remove(at: indexRemove)
    }
    if let indexRemove = textJson.firstIndex(where: { $0 == ">" }) {
        textJson.remove(at: indexRemove)
    }
    guard let data = textJson.data(using: .utf8),
          let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let result = json["result"] as? String
    else {
        showAlert(title: "Data Send", message: "FAIL")
        return
    }
    showAlert(title: "Data Send", message: result == "ng" ? "FAIL" : "SUCCESS")
}
```

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    let text = textFieldDataForWrite.text ?? ""
Same here, can you remove the leading space?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    func bleReadCharacteristic(uuid: CBUUID) {
Same here, can you remove the leading space and specify the language for the block?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    func peripheral(_ peripheral: CBPeripheral, didUpdateValueFor characteristic: CBCharacteristic, error: Error?) {
Same here, can you remove the leading space and specify the language for the block?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +```
Same here, can you remove the leading space and specify the language for the block?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    func peripheralManager(_ peripheral: CBPeripheralManager, didReceiveWrite requests: [CBATTRequest]) {
Same here, can you remove the leading space and specify the language for the block?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    private func bleSendIndication(_ valueString: String) {
Same here, can you remove the leading space and specify the language for the block?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +* [Core Bluetooth Tutorial](https://www.raywenderlich.com/231-core-bluetooth-tutorial-for-ios-heart-rate-monitor) by Raywenderlich
```suggestion
- [Transferring Data Between Bluetooth Low Energy Devices](https://developer.apple.com/documentation/corebluetooth/transferring_data_between_bluetooth_low_energy_devices) by Apple (with sample code, Central and Peripheral)
- [The Ultimate Guide to Apple’s Core Bluetooth](https://punchthrough.com/core-bluetooth-basics/) by PunchThrough
- [Core Bluetooth Tutorial](https://www.raywenderlich.com/231-core-bluetooth-tutorial-for-ios-heart-rate-monitor) by Raywenderlich
```

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    }
Can we format this block of code?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +    }
Can we format this block of code?

2022-09-06 04:07 UTC, zlatanpham commented on Engineering/Mobile/ios_bluetooth_low_energy/ios_bluetooth_low_energy.md
> +```
```suggestion
```swift
```

2022-09-06 04:08 UTC, zlatanpham commented
@viettrungphan can you take a look too?

2022-09-12 15:14 UTC, viettrungphan commented
There are some things should not in the sample code related to security, I will discuss with him separately and guide him how to fix it. Do not merge. Thanks @zlatanpham @monotykamary.

2022-09-14 04:15 UTC, closed without merging