threejs: cameras in ThreeJS
dwarvesf/brain pull request #93
Opened 2022-09-15 07:44 UTC by nguyend-nam

#### What's this PR do?

- [x] Add basic information about cameras in ThreeJS

2022-09-15 08:10 UTC, ngolapnguyen requested changes
Might also consider adding in some existing ThreeJS samples (or your own CodePen) showcasing `PerspectiveCamera` and `OrthographicCamera`. I think that would help making the points of this article much clearer.

2022-09-15 08:10 UTC, ngolapnguyen commented on Engineering/ThreeJS/Cameras in ThreeJS.md
> +ThreeJS is a JavaScript 3D library that allows developers to develop and describe data in 3 dimensions, and then convert them into 2 dimensions and display them on HTML Canvas. **Camera** is one of t
It'd be great if we can also have the articles for them in `brain`, covering all the basic of ThreeJS. But at the moment I think using external docs is good enough.

2022-09-15 08:10 UTC, ngolapnguyen commented on Engineering/ThreeJS/Cameras in ThreeJS.md
> +tags: engineering/threejs, threejs, camera
I think this should be `engineering/frontend/threejs`.

2022-09-15 08:10 UTC, ngolapnguyen commented on Engineering/ThreeJS/Cameras in ThreeJS.md
> +- **fov** (field of view): Camera frustum vertical field of view, i.e. the angle of the view in the yOz plane, in degree. The lower the number, the narrower the view.
Would be great if we have an illustration for fov in 3D space. Understanding fov in 3D context could be difficult.

2022-09-21 00:05 UTC, zlatanpham approved these changes
LGTM. @monotykamary might we test the image plugin here?

2022-09-21 04:54 UTC, monotykamary commented
ORPHAN COMMIT FOR REFLOG: [0c9b6aa20a4fc5c56de015b372ec9e8b732580a6](https://github.com/dwarvesf/brain/commits/0c9b6aa20a4fc5c56de015b372ec9e8b732580a6)

2022-09-21 04:59 UTC, monotykamary commented
> LGTM. @monotykamary might we test the image plugin here?

Looks all good 👍 

```diff
From d3d4f5d7097a2c89a92b0c7124d0a108d58bbc3b Mon Sep 17 00:00:00 2001
From: Tom Nguyen <tom81094@gmail.com>
Date: Wed, 21 Sep 2022 11:51:39 +0700
Subject: [PATCH] chore: generate local images

---
 Engineering/ThreeJS/Cameras in ThreeJS.md |  10 +++++-----
 _assets/OIpfGw7.png                       | Bin 0 -> 467251 bytes
 _assets/Va74b4E.png                       | Bin 0 -> 159737 bytes
 _assets/ZKOiIim.png                       | Bin 0 -> 505216 bytes
 _assets/cX1U9zI.png                       | Bin 0 -> 507573 bytes
 _assets/uIocTAX.png                       | Bin 0 -> 377219 bytes
 6 files changed, 5 insertions(+), 5 deletions(-)
 create mode 100644 _assets/OIpfGw7.png
 create mode 100644 _assets/Va74b4E.png
 create mode 100644 _assets/ZKOiIim.png
 create mode 100644 _assets/cX1U9zI.png
 create mode 100644 _assets/uIocTAX.png

diff --git a/Engineering/ThreeJS/Cameras in ThreeJS.md b/Engineering/ThreeJS/Cameras in ThreeJS.md
index bc61010..2936f70 100644
--- a/Engineering/ThreeJS/Cameras in ThreeJS.md	
+++ b/Engineering/ThreeJS/Cameras in ThreeJS.md	
@@ -14,19 +14,19 @@ You cannot use the `Camera` class directly to initialize a new camera in ThreeJS
 
 The image below shows the object viewed in **perspective camera** (upper) and in **orthographic camera** (lower).
 
-![](https://i.imgur.com/Va74b4E.png)
+![](_assets/Va74b4E.png)
 
 Place them into the **Oxyz** coordinate...
 
-![](https://i.imgur.com/uIocTAX.png)
+![](_assets/uIocTAX.png)
 
 ### Perspective camera
 
-![](https://i.imgur.com/OIpfGw7.png)
+![](_assets/OIpfGw7.png)
 
 Some crucial attributes:
 - **fov** (field of view): Camera frustum **vertical** field of view, i.e. the angle of the view in the yOz plane, in degree. The lower the number, the narrower the view.
-![](https://i.imgur.com/ZKOiIim.png)
+![](_assets/ZKOiIim.png)
 - **near** and **far**: Clipping planes at 2 points on the z axis. Note that objects with z position outside the `(near, far)` interval will **not** be displayed.
 
 ```javascript
@@ -42,7 +42,7 @@ Perspective camera visualization from [r105.threejsfundamentals.org](https://r10
 
 ### Orthographic camera
 
-![](https://i.imgur.com/cX1U9zI.png)
+![](_assets/cX1U9zI.png)
 
 Some crucial attributes:
 - **left**, **right**, **top** and **bottom**: Horizontal and vertical position of 4 segments of the view.
```

2022-09-21 05:25 UTC, merged